### ISSUE TITLE
Startup Crash With Kiwi mod.

### ISSUE THREAD

**Issue by QuerrixTU** [Fuzss/diagonal-blocks#1]
Hey !
I found a conflict between Diagonal Fences and Kiwi.

The game simply crash at startup.
![2021-04-13_21 28 13](https://user-images.githubusercontent.com/44301023/114609537-34881a00-9c9f-11eb-9827-5295bb2804e3.png)

Crash report:
https://pastebin.com/A7TB2Epe

Logs :
https://pastebin.com/KHGWgnVg

Debugs :
https://pastebin.com/MmVWhfRm

Informations :

Minecraft 1.16.5
Forge 36.1.4
Diagonal Fences1.0.1
Snow Real Magic 2.5.4
Kiwi 3.5.0

**Comment by QuerrixTU** [comment]
The last Version of Snow Real Magic fixed that

**Comment by Fuzss** [comment]
Yeah, I know. I'll also push some changes in v1.0.3 to make sure something like that doesn't happen again in the future with some other mod.
