### ISSUE TITLE
Dependency classload time leads to undiagnosable crash

### ISSUE THREAD

**Issue by lukebemish** [Fuzss/diagonal-blocks#13]
I noticed this oddity while helping a user diagnose a crash. They had diagonal fences installed, but not puzzles lib, and the game was crashing in a way that failed to show up in the log - best I can tell, this is because your mixin to FenceBlock gets loaded, and causes PuzzlesLib to be loaded, too early in the process for forge to catch what is going on, or even for forge to write useful information to the log (The debug and latest logs contained no information about the issue, ending directly after some mixin information, while the issue was visible from the launcher log). This could be fixed by moving `DIRECTION_TO_PROPERTY_MAP` out of `EightWayBlock`, so that loading `EightWayBlock` does not immediately trigger the load of your library. I will probably put together a pull request for this, as it seems simple enough.

**Comment by lukebemish** [comment]
(I realized that the cause of this issue is likely something else, and that forge, though it did not log it's normal full length information, still had some debug information)

**Comment by XFactHD** [comment]
You are very likely correct with your initial analysis. This kind of stuff is the main reason for hard to diagnose startup crashes in Forge mods.
I am not sure whether your proposed fix would help though, that depends on where that map is used. I haven't looked at the code yet to check that.

**Comment by lukebemish** [comment]
Basically, best I can tell: if you could defer all calls to the library until after mod initialization, there would be no issues. I've done some digging, though, and it looks like this would be very hard to do, if not outright impossible. The main issue, that I can tell, is that the class not found exception doesn't get logged in latest.log; not quite sure what's up with that.

**Comment by lukebemish** [comment]
The main issue here, and the reason I closed the issue after opening it, is that that map will get referenced no matter what when the mixins to fence blocks are called, just based on how they work. I do wonder why FML doesn't log stuff like this, but I don't know enough about FML to say.

**Comment by XFactHD** [comment]
To be fair, the library method that is referenced in the mixin is basically equivalent to a method in one of the vanilla util classes, so it should be possible to replace that method with the vanilla method to avoid this specific issue.
I'll take a look at this after a few hours of sleep to see if that's enough.

**Comment by lukebemish** [comment]
Yeah; forge does log the missing dependency, but at present the log just seems to cut off with no apparent cause.

**Comment by XFactHD** [comment]
Works fine and properly shows the loading error screen with the change I mentioned, so that's an easy fix.
