### ISSUE TITLE
Maintaining a private 1.18.1 port

### ISSUE THREAD

**Issue by nivthefox** [Fuzss/diagonal-blocks#14]
Hi!  Wasn't sure how else to reach you. Given this is currently released under MPL, and what not, would you be opposed to me taking a snapshot of your current release and backporting it to 1.18.1 for my private server?  I would not distribute it in that way to anyone other than my 4-5 players, and I would not allow them to submit bug reports to you (I will field any reports and test them in 1.18.2 before submitting them to you).

Is that alright by you?

**Comment by Fuzss** [comment]
Sure, go ahead!

**Comment by nivthefox** [comment]
Thank you!
