### ISSUE TITLE
Crash w/ Ore Stone Variants Mod

### ISSUE THREAD

**Issue by WenXin20** [Fuzss/diagonal-blocks#2]
`Minecraft v1.16.5`
`Forge v36.1.4`
`Diagonal Fences v1.0.3`
[`OSV v6.1`](https://www.curseforge.com/minecraft/mc-mods/ore-stone-variants)

When the mod Ore Stone Variants is installed and the config setting `overlaysFromRP` in `OSV-client.toml` is set to true, the game will crash on load. It looks to be related to the assets generator.
[Crash Report](https://gist.github.com/WenXin20/7dec90275728115655420848b953303d)
[Logs](https://gist.github.com/WenXin20/af6352e8e6ee58de0ff804a2271b77cb#file-latest-log-L2873)

**Comment by Fuzss** [comment]
Fixed in v1.0.4.

**Comment by WenXin20** [comment]
Thanks!
