### ISSUE TITLE
[Suggestion]: Compatibility with MrCrayfish's Furniture Mod?

### ISSUE THREAD

**Issue by ladypluu** [Fuzss/diagonal-blocks#20]
### Suggestion (Required)

Heya! Currently MrCrayfish's Furniture Mod's fences don't work with this, but it would be fun to see compatibility with them if that's a possibility for the future!

**Comment by Fuzss** [comment]
Yeah they don't work at all, since that mod doesn't extend vanilla fences.

**Comment by Fuzss** [comment]
So I'd rather focus on making Diagonal Fences more stable and add new features to it such as diagonal fences gates and walls, so mod compat such as this probably isn't happening.
