### ISSUE TITLE
[Bug]: Lagginess w/ Macaw's Fences and Walls

### ISSUE THREAD

**Issue by ladypluu** [Fuzss/diagonal-blocks#21]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19

### Mod Version (Required)

4.0.1

### Notes (Required)

1. Add mod file _mcw-fences-1.0.5-mc1.19.jar_ and _diagonalfences-v4.0.1-1.19_ to .minecraft/mods
2. Launch game & open world
3. Game becomes unbearably laggy

I tested this with MrCrayfish's Furniture mod and it doesn't produce the same effect. Macaw's Fences and Walls works fine without Diagonal Fences installed, unfortunately.

**Comment by Fuzss** [comment]
Does your world have a lot of fences from Macaw's? Can you share it maybe?
Do you also have these issues with just  Diagonal Fences?

I'm not having any issues at all honestly, even after placing a bunch of Macaws fences.

**Comment by gousisme** [comment]
same here, but I'm using this mod with a lot of other mods, another thing is I can't reload the resource (nor change the language) with this mod installed, it will freeze my PC, and most of the time it will crash, but sometimes the game will say out of memory.

**Comment by Fuzss** [comment]
How much ram have you allocated to mc?

**Comment by gousisme** [comment]
I've tried with 4GB, 6GB and 8GB, still laggy even the world is completely new (no fence placed), and yes i still can't reload the resource or change the language either.

**Comment by Fuzss** [comment]
Is your pack publicly available somewhere so I can test this myself? Can you maybe provide a download link or publish the pack on CurseForge?

**Comment by gousisme** [comment]
[lag.zip](https://github.com/Fuzss/diagonalfences/files/9383099/lag.zip)
Here you go, I just created a new profile with a few mods, just try to change the language with it

**Comment by Fuzss** [comment]
Fixed in v4.2.4.
