### ISSUE TITLE
[Bug]: Not showing diagonal connections with texture pack

### ISSUE THREAD

**Issue by Mohotzgui** [Fuzss/diagonal-blocks#23]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.1

### Mod Version (Required)

all so far

### Notes (Required)

When the mod wasn't updated I added a texture model to my personal pack that made some of the fences and walls arch when put at a corner (no where as satisfying as your mod. I am trying to purge those  out again for the most part but even one appears to conflict and cause the mod to not display, Is there a model JSON for your fences that I can experiment with the pack with? I like both models and would like to see where the conflict is. I am updating to the newest in hopes that may fix it.

**Comment by Fuzss** [comment]
The underlying system for generating diagonal connections was changed from using a resource pack based approach in 1.16 to an in-code conversion in 1.18+ to allow better support for modded fences.

The system loops through the multipart model to find the individual side connection models for all four directions, then rotates those by 45 degrees and adds them as additional models to the multipart model for the intercardinal directions.

If just made a quick change in this custom version to disable any model processing the mod does when at least one of the intercardinal directions is already defined in the json model, this should hopefully allow for your resource pack to work. I don't have a resource pack to test ready, so it would be great if you could provide some feedback.

https://mega.nz/file/2V9GAIBI#7pwv0PHLO5KFxFzpUdSua9bm48x1L7KIUCTMVbjaxGU

**Comment by Fuzss** [comment]
Just made a quick test pack myself and everything works. Feel free to use it as a template for your own pack.

The pack only modifies the acacia fence model, it's the same as the model that would otherwise be generated by the mod; to tell the difference I just left out one of the arms.

https://mega.nz/file/jFdw0T7Y#KqEAdkqwV64yOc2c8AeUaCvIpqvc-v0by9r0wzxxfig
