### ISSUE TITLE
[Crash]: Fabric 1.19.2

### ISSUE THREAD

**Issue by ardissaps** [Fuzss/diagonal-blocks#24]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.2

### Notes (Required)

Crashing

### Crash Report (Required)

https://mclo.gs/r1g4COk

**Comment by Fuzss** [comment]
Please try Puzzles Lib v4.2.2, does it solve your issue?

**Comment by ardissaps** [comment]
> Please try Puzzles Lib v4.2.2, does it solve your issue?

Yes, it works now, thank you!
![image](https://user-images.githubusercontent.com/82106625/185897206-e245d8f2-cafe-44a9-9c82-25325cae83c7.png)

Bonus Question : Will be there a wall version in the future?

**Comment by Fuzss** [comment]
Awesome!

Yes, I want to have walls, glass panes/iron bars and fence gates in the future.
