### ISSUE TITLE
[Bug]: Invincible diagonal fences with LambdaBetterGrass

### ISSUE THREAD

**Issue by BraggestHat010** [Fuzss/diagonal-blocks#25]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.2.0

### Notes (Required)

placing fences with the fabulously optimized modpack makes the diagonal fences invincible. 

![2022-08-26_01 19 47](https://user-images.githubusercontent.com/112134473/186785144-7051cf11-853e-46fe-938a-b50c601d4cf0.png)
e

**Comment by Fuzss** [comment]
Waiting for a response on this: https://github.com/LambdAurora/LambdaBetterGrass/issues/58
For now you can remove the conflicting mod.

**Comment by SplendidAlakey** [comment]
Just chiming in to say that, at least on the latest versions of all mods, it's only the vanilla fences that fail to render diagonally. Modded ones work.

![2022-09-14_09 24 50](https://user-images.githubusercontent.com/86702831/190091470-f952a4c9-a6b7-47c4-8e92-a322d8cf79fe.png)

**Comment by Fuzss** [comment]
Probably because LambdaBetterGrass only changes the models for vanilla fences, Diagonal Fences affects all fences though.

**Comment by SplendidAlakey** [comment]
Ah, makes sense. Hopefully Aurora responds soon.

**Comment by Fuzss** [comment]
I went ahead and added integration for Lambda Better Grass in Diagonal Fences v4.2.2.
![2022-10-12_14 01 53](https://user-images.githubusercontent.com/28218241/195338320-8663e586-a453-446f-9b0a-3938c07e99fd.png)
