### ISSUE TITLE
[Bug]: Memory usage soars after loading the world

### ISSUE THREAD

**Issue by Dr-WeiAL** [Fuzss/diagonal-blocks#26]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.18.2

### Mod Version (Required)

3.1.0

### Notes (Required)

The memory usage comparison is as follows
![image](https://user-images.githubusercontent.com/47446553/187264016-58c774ac-de0a-40af-95f1-b1d41136103f.png)
![image](https://user-images.githubusercontent.com/47446553/187264478-8da727e5-a21d-47bb-a2c5-b12ef0fb7c5a.png)

![image](https://user-images.githubusercontent.com/47446553/187264645-d2cbe348-aa68-4ea6-a98c-6992fba51aaf.png)

This is more serious in my modpack
![image](https://user-images.githubusercontent.com/47446553/187267987-d8415f5c-0ff1-4f4c-9de2-b2b6eeb33724.png)
![image](https://user-images.githubusercontent.com/47446553/187269181-491aeb94-fa4e-47e8-a77f-779a7a3ae26b.png)

### latest.log (Optional)

https://gist.github.com/Dr-WeiAL/17a156e8c52be5f8e3de31607ac4f393

**Comment by Fuzss** [comment]
Does Furnish have fences with diagonal connections from Diagonal Fences?

**Comment by Dr-WeiAL** [comment]
Furnish doesn't have fences, because I have too many mods in the mod pack, so I can only pull out some mods for testing.

**Comment by Dr-WeiAL** [comment]
I tested it in detail, and installing Diagonal Fences or Macaw's Fences alone will not cause memory overflow, but installing both at the same time will cause memory overflow

**Comment by P3rf3ctXZer0** [comment]
https://github.com/P3rf3ctXZer0/P3rf3ctXZer0s-Workshop/issues/2
I concur. I added my information.

**Comment by 5stigma** [comment]
Confirm!. I have several mods with fences, and it consumes me 4GB extra and without the mod it only consumes 8GB. I have 12GB allocated for testing and it consumes everything, I have a feeling that if I allocate more it will eat everything.

**Comment by Fuzss** [comment]
Fixed in v4.2.4 for 1.19.2. Will do a backport to 1.18.2 hopefully soon.
