### ISSUE TITLE
[Crash]: Crashes before loading screen completes

### ISSUE THREAD

**Issue by paustin123** [Fuzss/diagonal-blocks#27]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.18.2

### Mod Version (Required)

V3.1.0

### Notes (Required)

1. launch game
2. load pack
3. crashes before loading screen completes. 

### Crash Report (Required)

https://gist.github.com/paustin123/2d602f809d7e931d2d3190ee2223098e

**Comment by Fuzss** [comment]
How much ram do you have allocated?

**Comment by paustin123** [comment]
> How much ram do you have allocated?

Originally my pack runs with only 8.5GB allocated. When i got this error I raised it to 10, 12, and then 14GB. The only thing it did was delay the crash by a couple minutes each time.  Removing the mod brings it back to 8.5 and launches normally.

**Comment by paustin123** [comment]
> > How much ram do you have allocated?
> 
> Originally my pack runs with only 8.5GB allocated. When i got this error I raised it to 10, 12, and then 14GB. The only thing it did was delay the crash by a couple minutes each time.

Removing the mod pack launches fine at 8.5GB

**Comment by Fuzss** [comment]
Fixed in v4.2.4 for 1.19.2. Will do a backport to 1.18.2 hopefully soon.
