### ISSUE TITLE
[Bug]: Can't see diagonal connections

### ISSUE THREAD

**Issue by wanhose** [Fuzss/diagonal-blocks#28]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.2.1

### Notes (Required)

Got this result using Better MC modpack v4 and Sildur's Vibrant shaders v1.40 Lite... is there any compatibility issue between them? I tried to disable shaders but the problem still persists and they are just spruce fences from vanilla.

<img width="652" alt="image" src="https://user-images.githubusercontent.com/50265843/189187846-86a88dad-90fb-434d-acc9-1f1da7ae5578.png">

Also the resource packs applied are from these mods, adding nothing to the resource packs folder.

<img width="416" alt="image" src="https://user-images.githubusercontent.com/50265843/189189695-a3b4dfc2-079b-4c66-9472-c376b2f46fad.png">

**Comment by Fuzss** [comment]
Do you have lambda better grass?

**Comment by wanhose** [comment]
Just checked but no, I don't.

**Comment by ArnyminerZ** [comment]
Same here on Fabric `0.14.9`. No resource packs, no shaders enabled still causes the issue.

**Comment by SplendidAlakey** [comment]
I'm able to reproduce the issue without any mods other than Diagonal Fences. Logs don't print any issues.

**Comment by Fuzss** [comment]
Thanks for the reports, I can confirm this as an issue introduced in Puzzles Lib v4.3.0+.
If Diagonal Fences is the only one of my mods you're using I recommend downgrading Puzzles Lib to v4.2.4. Otherwise I'll try to publish a new version tomorrow.

**Comment by Fuzss** [comment]
Fix is out, please update Puzzles Lib to v4.3.2.

**Comment by ArnyminerZ** [comment]
The issue is still there for me on Puzzles Lib `4.3.2`, Diagonal Fences `4.2.1`, Minecraft `1.19.2` and Fabric Loader `0.14.9`.

![2022-09-13_15 31 25](https://user-images.githubusercontent.com/12086466/189914917-7e6f926f-4281-42f7-8097-9e5d29752b45.png)

**Comment by Fuzss** [comment]
With just Diagonal Fences + Puzzles (+Forge Config Api)?

I tested just those and they were fine with the new Puzzles version.

**Comment by ArnyminerZ** [comment]
Totally fine with just that mods.

![image](https://user-images.githubusercontent.com/12086466/189923366-5c2a4d59-9baf-469c-8a4a-e780ee628be9.png)

![2022-09-13_16 09 36](https://user-images.githubusercontent.com/12086466/189923567-7911ae96-2681-40c6-875c-fc88b7355440.png)

I'll try now with other mods that might be problematic such as Sodium, Lithium...

**Comment by ArnyminerZ** [comment]
Checklist (will update once I test):

- [x] Sodium
- [x] Sodium Extra
- [x] Lithium
- [x] Iris (+Complementary Shaders)
- [ ] Starlight
- [ ] Indium

**Comment by Fuzss** [comment]
Lambda Better Grass is known to break the rendering. Do you maybe have that?

**Comment by ArnyminerZ** [comment]
Yes, that's totally the issue. Lambda Better Grass breaks the rendering. I'll remove it.
