### ISSUE TITLE
Doesn't work with optifine

### ISSUE THREAD

**Issue by resooox** [Fuzss/diagonal-blocks#29]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.2.2

### Notes (Required)

1. Load minecraft with diagonal fences mod and optifine
2. press play
3. doesnt boot

**Comment by Fuzss** [comment]
Has nothing to do with OptiFine, that works fine.
Install Puzzles Lib, Diagonal Fences requires it to run.
