### ISSUE TITLE
Colorizer Fence doesn't visually connect

### ISSUE THREAD

**Issue by WenXin20** [Fuzss/diagonal-blocks#3]
`Minecraft v1.16.5`
`Forge v36.1.4`
`Diagonal Fences v1.0.5`
[`Assorted Decor v2.0.9`](https://www.curseforge.com/minecraft/mc-mods/assorted-decor)

I discovered that the colorizer fence from Assorted Decor will not visually connect to each other. (Which can be used with the colorizer wand to change the texture to any block.)

![2021-04-25_23 54 41](https://user-images.githubusercontent.com/12000593/116030786-fcc78d80-a621-11eb-9805-02b908f1b208.png)

**Comment by Fuzss** [comment]
That's unfortunate, I've now added those fences to the exclusion block tag by default, meaning the features of my mod no longer apply. There is no time for proper compatibility right now sadly.
