### ISSUE TITLE
[Bug]: Mob Pathfinding Through Diagonal Fence

### ISSUE THREAD

**Issue by Kowantify** [Fuzss/diagonal-blocks#30]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.2.3

### Notes (Required)

I recently was playing on a server I had created with friends, and everything was fine

After about a week we decided to make a quite large village using the diagonal fences for villager hotel rooms

We found that we would get an INSANE amount of TPS drops on a 5800x server, and it was insane, like 5tps

We couldn't point a finger to exactly what was causing it

I found that an entity was trying to navigate through a diagonal fence and the lag was fixed by breaking the fence that villager was trying to nav through

It was hard to replicate but I was able to by placing a bed next to a diagonal fence, and when the villager awoke the villager was almost in the diag fence but not entirely, and tried to path find through it

That's when the TPS drops ensued, none of the players experienced a actual FPS drop, just TPS

I apologize for not attaching the latest.log file from my server, as I am currently not able to access it in person, but wanted to at least put this on your radar, I will try to get a proper latest.log when I am able to create another quick test server with friends to purposely re-create the issue

**Comment by Fuzss** [comment]
Oh wow, that seems like a nasty issue... 
Could you show a screenshot of your setup where the villagers get stuck?

**Comment by Kowantify** [comment]
![2022-10-16_15 34 09](https://user-images.githubusercontent.com/35680697/196057056-4706205e-499d-455b-80ba-d09bcc41f422.png)
![2022-10-16_15 34 58](https://user-images.githubusercontent.com/35680697/196057057-abf13c9a-e47e-40c1-b652-b10a974c1500.png)

So I did some more testing, seems that mods that will turn mob path finding into a multi threaded task, seem to cause a the main TPS lag, (Rubidium and Minecraft Comes Alive Reborn)

Seems that vanilla wise it's not as bad, I didn't drop below 20tps,

I was only able to test it standalone like this on a client level and not server level, I think when it is on a dedicated server it is way way worse

The most confusing part... adult villagers / mca villagers are just fine with pathfinding, the only entity that seems to cause the TPS drop, is baby MCA villagers, so this may be an issue with MCA Reborns part, and not necisarily diagonal fences, because the base MC villagers arent dropping the TPS (atleast from testing)

The baby villagers won't pathfind out of the diagonal fence bed combo like shown in the photos attached, I am honestly confused but I know for sure, MCA Reborn Baby Villagers, and pathfinding through a diagonal fence causes insane TPS loss, but the MCA reborn mod from my understanding doesn't change the default pathfinding of vanilla villagers, not entirely sure but this is what I could provide

**Comment by Fuzss** [comment]
> but the MCA reborn mod from my understanding doesn't change the default pathfinding of vanilla villagers

But only MCA villagers are affected, right? So even with MCA vanilla villager children work fine?

More like a random guess, but does this version of MCA fix the issue for you?
https://mega.nz/file/XRVDRaAT#NZcJx9TRh7DwbXYAnOEIzjF3gvhYHI7JPYoRicOWcB4

**Comment by milkev** [comment]
i had this pathfinding issue playing on bettermc fabric 1.19.2, there was no lag but my chickens just sat in the corners of my fencing instead of wandering around like normal

**Comment by Fuzss** [comment]
vanilla mob ai is sometimes confused by blocks with odd collision boxes, there’s nothing i can really do
can you still maybe share a screenshot though?

**Comment by Fuzss** [comment]
@KowalskiXCIX any update on how the custom version i provided is doing?

**Comment by laserlemons** [comment]
Was this ever fixed? This issue was the only thing that kept me from adding it back into my modpack,

**Comment by Fuzss** [comment]
Yeah, see #40.
