### ISSUE TITLE
[Suggestion]: Improved visualization box?

### ISSUE THREAD

**Issue by Albhis** [Fuzss/diagonal-blocks#31]
### Suggestion (Required)

Would it be possible to create a voxel shape that looks less messy?
I ask since the vineblock class does a fancy thing where it adds all the shapes together and then makes the visual box, making the hitbox of the block not overlap (I assume that's what it does)

**Comment by Fuzss** [comment]
No, this is too much effort. The vanilla system isn't designed for diagonal pieces, just getting the diagonal connections to show was hard enough. Not going to implement a new algorithm to sort out any overlapping lines. Thanks for the suggestion though.
