### ISSUE TITLE
[Bug]: Hal's Exploration Mod Compat

### ISSUE THREAD

**Issue by mxnmnm** [Fuzss/diagonal-blocks#33]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.16.5

### Mod Version (Required)

1.1.1

### Notes (Required)

Does not work with fences from Hal's Exploration mod

**Comment by Fuzss** [comment]
Thanks for the report! The mod you mentioned unfortunately is closed source, so I can't easily look into what's going on. I'm assuming though they are using their own fence implementation separate from vanilla fences, which is not supported by Diagonal Fences.

Either way I'm also no longer actively maintaining mod versions for Minecraft 1.16.
