### ISSUE TITLE
[Bug]: Slight incompatibility with Snow! Real Magic!

### ISSUE THREAD

**Issue by eddy0820** [Fuzss/diagonal-blocks#34]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.2.3

### Notes (Required)

When using Snow! Real Magic! parts of the fence texture darkens when a diagonal fence post is near a block
![2023-01-04_23 18 57](https://user-images.githubusercontent.com/59713264/210700975-7c66d34c-24c1-4fae-9e96-569466898339.png)

**Comment by Fuzss** [comment]
Thanks for the report!

This is an issue with the vanilla model system, as it happens with neither Snow! Real Magic! nor Diagonal Fences installed (when the diagonal fence model is applied solely using a resource pack). So there’s nothing I will do about it.
