### ISSUE TITLE
[Bug]: Fences invisable

### ISSUE THREAD

**Issue by Eatham532** [Fuzss/diagonal-blocks#36]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.2.3

### Notes (Required)

I am guessing that this is happening because I am using an optifine resource pack. But there are nothing in the resource pack related to fences. Also using lambdabettergrass.

**Comment by Recheezy** [comment]
hey, I'm also having this issue, is there any sort of workaround until it's fixed for 1.19.2? because diagonal oak fences will be invisible and then not for a while until it happens again

**Comment by Eatham532** [comment]
Not that I know of. And yeh. Sometimes it works fine.

**Comment by Fuzss** [comment]
Do you still have this issue in v4.2.4?

**Comment by Boroso** [comment]
fuzss, yes modded diagonal fences are invisible but minecraft diagonal fences are normal @Fuzss version v4.2.3 fabric 1.19.2

**Comment by Fuzss** [comment]
@Boroso please be more specific, what fences from what mod? Which version etc

**Comment by Boroso** [comment]
im going to be more specific, any, literally any modded fence from any mod that adds fences right? their diagonal fences variant become invisible on v4.2.4, but on v4.2.3 this issue doesnt happen, i hope you understand please use ur brain if u didnt

**Comment by Fuzss** [comment]
@Boroso Be careful with your words. If you don‘t provide any specific mods and fences that no longer work I can‘t help you.

**Comment by Boroso** [comment]
> @Boroso Be careful with your words. If you don‘t provide any specific mods and fences that no longer work I can‘t help you.

hey i didnt say anything bad, why are u so rude and deleting my post for trying to help

**Comment by Eatham532** [comment]
Hey @Boroso he said he can't replicate the bug so he wont know how to fix it. Just be patient as development can be slow.

I have stopped playing mc but I can try to see if I replicate it. Last time I remember it the bug was still there. I am guessing some mod incompatibility

**Comment by Eatham532** [comment]
@Fuzss I did a test. The bug is still there. It seems that modded fences work but vanilla fences do not. 
![image](https://github.com/Fuzss/diagonalfences/assets/78714349/a82a1f9c-c989-460a-b02d-7e760aeb3a5f)

If you want to test it more I am using a custom modpack I made. The link is here: https://www.curseforge.com/minecraft/modpacks/peoplesmp

If you want anymore help just let me know. But I'm a bit busy and it may take a few days before I get to it.

**Comment by Fuzss** [comment]
Thanks for this! Would be great if you could when you find the time just do a binary search to find which mod is conflicting.

**Comment by Eatham532** [comment]
No problem. Yeh, I will try that when I get the chance.

**Comment by Fuzss** [comment]
Should no longer be an issue in the latest versions (anything since 8.1.0). If it comes back please open a new report on the new repository.
