### ISSUE TITLE
[Bug]: Players can still fall of the diagonal fence when sneaking

### ISSUE THREAD

**Issue by sophuric** [Fuzss/diagonal-blocks#39]
### Mod Loader

Fabric

### Minecraft Version

1.19.3

### Mod Version

5.0.0

### Notes

Steps to reproduce:
1. Place two fences diagonally of each other
2. Stand in-between the fences on top of them
3. Hold sneak
4. Walk off the fence

Expected behaviour:
Player does not fall of the fence like what would happen if the fences were next to each other not diagonally

Actual behaviour:
Player falls off the block as if they were not sneaking

**Comment by Fuzss** [comment]
Thanks for the report! I don't think I can fix this honestly, or at least it would require way more effort than it's worth.

Minecraft just isn't designed for what Diagonal Fences is doing, hence the mod is pushing the game engine a little too far in some scenarios such as this one. There are many other issues I'm aware that simply come down to this, like entities trying to pathfinding through diagonal fence connections, the absurd amount of block states fences now have, the insane internal complexity of diagonal collision boxes, the internal hacks it needs to even be able to render diagonal fence parts, etc.

I hope you see my point.
