### ISSUE TITLE
[Bug]: Animals obsessed with diagonal fences

### ISSUE THREAD

**Issue by twenty41** [Fuzss/diagonal-blocks#40]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.2.4

### Notes (Required)

Animals in pens constantly walk towards the diagonal portion. Perhaps they perceive it as being open when it's not.

To reproduce, just have a pen and have animals in it.

![Screenshot_1](https://github.com/Fuzss/diagonalfences/assets/46447750/6816105a-734d-43d5-8e5d-9d215bfd88bf)

**Comment by Fuzss** [comment]
Thanks for reporting! Fixed in v4.2.5.
