### ISSUE TITLE
[Crash]: Crash on startup

### ISSUE THREAD

**Issue by mxnmnm** [Fuzss/diagonal-blocks#41]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.18.2

### Mod Version (Required)

v3.2.0

### Notes (Required)

Crashes when I launch the game, likely a mod conflict but idk which one. This only happens on version v3.2.0 aka previous version booted just fine.

### Crash Report (Required)

https://gist.github.com/mxnmnm/6159506a969db0efb829c43e8cda3cba

**Comment by Fuzss** [comment]
Does it happen all the time or just randomly?

**Comment by XFactHD** [comment]
Also worth checking whether this still happens without the Lightspeed mod.

**Comment by Fuzss** [comment]
Or Modern Fix. It might be caused by this: https://github.com/Fuzss/puzzleslib/issues/41

**Comment by mxnmnm** [comment]
It happens every time and disabling lightspeed fixed it. Disabling modern fix did nothing.

**Comment by Fuzss** [comment]
Does this custom version of Puzzles Lib fix the issue with Lightspeed?
https://mega.nz/file/eEE0lIrI#UAGkuVLNeD6LbX-uEAeZBu3dQ-R0ljOkTLoVg6uveKA

**Comment by mxnmnm** [comment]
It worked :D

**Comment by xFirefalconx** [comment]
Having crashes on the new version, too. Incompatibilities with FramedBlocks. 
``java.lang.NoClassDefFoundError: fuzs/diagonalfences/api/IDiagonalBlock``

[crash-2023-06-06_15.54.02-client.txt](https://github.com/Fuzss/diagonalfences/files/11666800/crash-2023-06-06_15.54.02-client.txt)
[crash-2023-06-06_15.38.31-client.txt](https://github.com/Fuzss/diagonalfences/files/11666801/crash-2023-06-06_15.38.31-client.txt)

**Comment by Fuzss** [comment]
Fixed in v3.2.1. Although there is no crash anymore, Framed Blocks unfortunately fails to render diagonal fences connections due to some internal changes I had to make a few versions ago. I already told XFactHD about it and he is looking into it.
