### ISSUE TITLE
[Bug]: 1.18.2 Invisible fences

### ISSUE THREAD

**Issue by xFirefalconx** [Fuzss/diagonal-blocks#43]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.18.2

### Mod Version (Required)

3.1.1 (3.2.0 is still broken for me)

### Notes (Required)

The Star Worm Decor Mod adds a bunch of picket fences. They don't show up when connecting diagonally, though the bounding box and collider do exist. I tested it on a fresh pack with only DF, Puzzles Lib and SWDM installed, no shaders involved. Happened on my large modpack as well where I use Oculus and Flywheel compat. The fence never renders correctly, maybe a missing reference? 
![grafik](https://github.com/Fuzss/diagonalfences/assets/106652912/b9230ac3-6ad9-4cd2-b791-65a56d770d1c)

Please let me know if I should test any other fences! Sure can. I had no issues with other fences so far but I haven't used too many different types so I might be missing something. 
![grafik](https://github.com/Fuzss/diagonalfences/assets/106652912/b4a74524-5772-443d-99f4-fe14d10d422a)

If you need any other info, just ask! I try my best to provide so we can figure out what happened :)

**Comment by Fuzss** [comment]
Please add your latest.log file.

**Comment by xFirefalconx** [comment]
[latest.log](https://github.com/Fuzss/diagonalfences/files/11725336/latest.log)

**Comment by Fuzss** [comment]
Fixed in v3.2.1.
