### ISSUE TITLE
[Bug]: Blocks which arent fences are shown as fences

### ISSUE THREAD

**Issue by xsolane** [Fuzss/diagonal-blocks#44]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20

### Mod Version (Required)

1.20

### Notes (Required)

Hi, when I use the diagonal fence mod it makes blocks like carpet, player head items, stained glass and stairs look like fences. When i delete diagonal fence mod its gone. The fences look like its 2 fences stacked together in one block space (like a regular fence and diagonal fence in one block entity).

**Comment by Fuzss** [comment]
Are you playing on a server without Diagonal Fences installed on the server?

**Comment by xsolane** [comment]
oh yea i am, can i not use the mod in servers?

**Comment by Fuzss** [comment]
No.
