### ISSUE TITLE
[Bug]: Invisible diagonal BlockCarpentry fences (compat)

### ISSUE THREAD

**Issue by HanatakeYurii** [Fuzss/diagonal-blocks#45]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.2.5

### Notes (Required)

First, I have to say it's not a fatal bug, just visually missing.

So, similarly to issue #36, the diagonal parts of the fence don't show up, but this time it involves "coverable" ("framed", "illusion") fences from [BlockCarpentry](https://www.curseforge.com/minecraft/mc-mods/blockcarpentry). Due to the nature of these fences, I have no idea if you can do anything about this, but I still wanted to let you know.

If it's not fixable, one might suggest to disable diagonals for these (2) fences.

PS: BlockCarpentry's dev is currently over-stressed by their studies so not reachable for a long time, so I'll have to wait if the fix should be done on their side.

**Comment by Fuzss** [comment]
This probably needs dedicated compat for the block carpentry model, I won't be working on something like that, I'd rather just blacklist those fences. You can do so yourself using the `diagonalfences:non_diagonal_fences` block tag. If you provide the necessary ids here I can add them to the block tag by default in the next update. 

Also in case you are willing to consider an alternative to BlockCarpentry, [FramedBlocks](https://www.curseforge.com/minecraft/mc-mods/framedblocks) fully supports diagonal fences out of the box.

**Comment by HanatakeYurii** [comment]
Thanks for the suggestion but I wanted to avoid the "over-complexity" of FramedBlocks (not to mention some lighting issues for some frames and fears of performance issues on my server if players overdo it). 

Anyways I will take a look in a day or two to get the id(s), and see if I can manage to contact BlockCarpentry's author.
