### ISSUE TITLE
[Crash]: Crash when reloading resources

### ISSUE THREAD

**Issue by Fuzss** [Fuzss/diagonal-blocks#46]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.2.5

### Notes (Required)

getting this crash when trying to switch resource packs in prominence 1 forge

### Crash Report (Required)

https://gist.github.com/Fuzss/b2d91ee1ca3193a391a783e87545252f

**Comment by rohanverma2007** [comment]
Receiving this bug as of recently as well

**Comment by Fuzss** [comment]
I posted a test release on our [Discord](https://lunapixel.studio/discord), feel free to check if it solves the issue. Can't reproduce this myself, so I'm not completely sure if I got it.

**Comment by Fuzss** [comment]
Fixed in latest versions.
