### ISSUE TITLE
[Bug]: Turns kelp into fence

### ISSUE THREAD

**Issue by Unimatrix36** [Fuzss/diagonal-blocks#48]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.0

### Notes (Required)

When I play on a server, any server, the mod turn the kelp under water into fence columns.
When I remove the mod the kelp is back.
When I add the mod again it's fence.
It also turns glowstone and command blocks into fence.

It only happens when I play on servers, not single player.
Every time I want to play on servers I have to remove the mod.

The game also get really laggy when I play on servers.
When I remove the mod it's back to normal.

**Comment by Fuzss** [comment]
Diagonal Fences is required on both the client and server when playing. If you want to play on a server without the mod remove Diagonal Fences from your client, there is no way around it.
