### ISSUE TITLE
Crash on startup with PuzzlesLib 1.0.3 or newer

### ISSUE THREAD

**Issue by enduum** [Fuzss/diagonal-blocks#5]
Diagonal Fences launches perfectly fine with PuzzlesLib 1.0.2, but versions 1.0.3-1.0.6 all crash on startup with the same error message.

[latest.log](https://pastebin.com/HP8HGG7P) (using 1.0.6 of PuzzleLib)
[crash report](https://pastebin.com/CWY7AdsK)

Versions:
Minecraft 1.16.5
Forge 36.1.32 (latest as of writing)
Diagonal Fences 1.1
Tested on a clean instance with no other mods.

**Comment by Fuzss** [comment]
You need to update Diagonal Fences to v1.1.1.

There had to be some breaking changes in Puzzles Lib v1.0.3 unfortunately as the previous implementation wasn't working very well.

**Comment by enduum** [comment]
😳 Sorry for the bogus report, I straight up didn't see that last .1 in the filename and thought 1.1 was the most recent version.
