### ISSUE TITLE
[Suggestion]: Make it compatible with "Oh The Biomes You'll Go" and "Traverse"

### ISSUE THREAD

**Issue by shiniebub** [Fuzss/diagonal-blocks#51]
### Suggestion (Required)

Currently, all three mods are completely functional together. However, it's missing textures; In the given image, these two Lament type fences connect diagonally, but don't appear to be: https://i.imgur.com/tpqhUYJ.png

Similar issue appears with Traverse mod fences.

**Comment by Fuzss** [comment]
Please try with just Diagonal Fences and the biome mods installed (+dependencies). This is not an issue for me on the latest version, everything renders and functions as it should.

**Comment by shiniebub** [comment]
Will try, thank you for the suggestion.
It seems I have made a fool of myself yet again with my fast paced and addled brain.

**Comment by vgrynch** [comment]
Worked for me for all BYG fences in a pack with 200+ mods. Must be some rendering issue. Are you using Optifine?
