### ISSUE TITLE
[Suggestion]: auto-update placement when structrues place with fences

### ISSUE THREAD

**Issue by vgrynch** [Fuzss/diagonal-blocks#52]
### Suggestion (Required)

(1.19.2) When the structure is placed by world generating, fences inside of the structure do not automatically connect as diagonal. For example:
![image](https://github.com/Fuzss/diagonalfences/assets/46818018/7744acc7-77f1-45c4-830c-61c9c4757367)

Would be good to have them connect automatically right away without the need to do a manual update, like this:
![image](https://github.com/Fuzss/diagonalfences/assets/46818018/669df434-f746-4190-b657-a46576651f3d)

I understand I can save the new structrue nbt with fences already connected in it, but I think some support of existing structures would be good to have.
(The structure I used in the above examples is Wabi sabi structures - "llama_sanctuary_plateau" - it contains Llama holding places)

**Comment by Fuzss** [comment]
I don't think it's possible to update fences placed by structures if they didn't contain the diagonal block states in the first place.

**Comment by vgrynch** [comment]
Any advise on how I can possibly update them via data packs? I know there is a way to pre-process structure blocks before placing them into the world, but I'm not familiar with that.

**Comment by Fuzss** [comment]
Editing the nbt files seems to be the only option. I think the Repurposed Structures dev might have some tools for that, maybe ask them.
