### ISSUE TITLE
[Bug]: Blocks placed become completly different Blocks

### ISSUE THREAD

**Issue by f0kx** [Fuzss/diagonal-blocks#53]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.2.6

### Notes (Required)

When you Mod is installed i have a wiered stuff happening. Whenever i place blocks which are connected (fences, walls or placing blocks with effortless building) they became (when i play on server side) completly differnt blocks. I need to reload the chunk or rightclick them with my hand that they become the correct one.
After i delete your Mod this will not happening any more.

![image](https://github.com/Fuzss/diagonalfences/assets/14795020/812f6e3b-d84d-42cf-8815-78d46b65533d)
here you see i have a fence and place it and it becomes iron doors and waterlogged fences.
![image](https://github.com/Fuzss/diagonalfences/assets/14795020/0df01610-ee54-409f-a438-08fb753aa5e2)
here i rightcllicked few of them and place on new down and it became a jukebox.

When i deinstall your mod i can place new added modblocks completly free of any bugs

**Comment by f0kx** [comment]
and all mods are the same in server and client because i ask everywhere what causes by this and checked it 10000x times.

**Comment by Fuzss** [comment]
Thanks for reporting. Seems to be the same issue as mentioned here which is caused by a vanilla bug: https://github.com/Fuzss/diagonalwindows/issues/3

**Comment by f0kx** [comment]
is the mod he mentioned downloadable?
