### ISSUE TITLE
[Bug]: BetterEnd diagonal fences are invsisible

### ISSUE THREAD

**Issue by MrGreenTea** [Fuzss/diagonal-blocks#54]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.0.1

### Notes (Required)

[BetterEnd](https://modrinth.com/mod/betterend) adds new woods and with that fences.

For some reason it looks like this when placed diagonally:

![2023-10-23_14 54 56](https://github.com/Fuzss/diagonalfences/assets/9407731/5ee7fea7-1f1f-4e4a-a1f9-5447b53f96aa)

**Comment by Fuzss** [comment]
I saw that Better End generates custom block models for fences, so those aren't compatible.

It would be best if you would simply add the fences from Better End to the `diagonalfences:non_diagonal_fences` block tag, so they are excluded. If you send me the list of ids I can include them by default.

**Comment by MrGreenTea** [comment]
@Fuzss Yeah I've noticed that Better End does some incompatible things with other mods too. I've removed it from my mods because of that and can't easily provide the item IDs at the moment, sorry.

**Comment by Fuzss** [comment]
No worries. I quickly filtered out the ids on my own and they are now excluded by default.
