### ISSUE TITLE
[Crash]: Diagonal Blocks (diagonalblocks) has failed to load correctly

### ISSUE THREAD

**Issue by X-Machiavelli** [Fuzss/diagonal-blocks#56]
### Mod Loader (Required)

NeoForge

### Minecraft Version(s) (Required)

1.21.1

### Mod Version(s) (Required)

v21.0.0

### Other Mods Involved (Required)

Yes

### Notes (Required)

![image](https://github.com/user-attachments/assets/a216cc9b-22d0-495f-9e55-d25e467095d8)
[crash-2024-09-16_15.00.30-fml.txt](https://github.com/user-attachments/files/17009113/crash-2024-09-16_15.00.30-fml.txt)
[latest.log](https://github.com/user-attachments/files/17009114/latest.log)
client side mod loading error.

### Crash Report (Required)

https://gist.github.com/X-Machiavelli/e3a1106a1f7f818f735cf26622a8c3d1

### latest.log (Optional)

https://gist.github.com/X-Machiavelli/8dc6baba4011b3a010c4c82e9e5d20ed

**Comment by Fuzss** [comment]
1.21.1 version is out now.
