### ISSUE TITLE
Unknown resource pack type

### ISSUE THREAD

**Issue by TheIrishStud** [Fuzss/diagonal-blocks#6]
Debug log Render thread/Warn "mod_resources" logs com.fuzs.diagonalfences.resources.RuntimeResourcePack @7443a906 as an Unknown resource pack type. Might be caused by some mod conflicts so take this info with a grain of salt.

**Comment by Fuzss** [comment]
That is to be expected as this mod uses a virtual resource pack to provide assets for the diagonal fences. I think the message comes from OptiFine, but it shouldn't cause any issues.
