### ISSUE TITLE
Snow! Real Magic! Incompatability

### ISSUE THREAD

**Issue by AllieSniperian** [Fuzss/diagonal-blocks#7]
When Diagonal Fences is installed in the same game as "Snow! Real Magic!" anytime a fence gets snow'ed over it loses the ability to connect diagonally.

[Snow! Real Magic!](https://www.curseforge.com/minecraft/mc-mods/snow-real-magic)

**Comment by Fuzss** [comment]
Make sure you have at least v2.5.5 of Snow! Real Magic! and it should work fine.
