### ISSUE TITLE
Quite weird shaded part of the fence

### ISSUE THREAD

**Issue by Toma400** [Fuzss/diagonal-blocks#9]
Using river fences (Upgrade Aquatic), I made a fence around my house. For some weird reason, one part of it has glitched shade on it:

![2022-02-05_22 28 49](https://user-images.githubusercontent.com/65849429/152659665-7192bd66-0cf6-4c0c-b4f7-6466aae021a5.png)

Not sure what I should include aside from this screenshot, so please tell me if anything is needed.

**Comment by Fuzss** [comment]
Thanks for the report, there’s nothing I can do though. That’s a glitch with the vanilla rendering system. It occurs when you place a fence next to a full block (in your case the wooden planks). 

I‘m doing nothing special for the rendering, just normal json model files, so yeah, that’s a vanilla big unfortunately.

**Comment by Fuzss** [comment]
Closing this now since there's nothing I can do about it.
As mentioned it's a bug with the vanilla system, you'd get the same result applying the model with a resource pack without any mods.
